packages:
  - addons/*
  - electron

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - unrs-resolver

patchedDependencies:
  eslint-plugin-prettier: patches/eslint-plugin-prettier.patch
