packages:
  - addons/*
  - electron
  - sculptcore/tests
  - sculptcore/source/litestl/binding/typescriptRuntime
  - sculptcore/source/litestl/tests
  - sculptcore/typescript
  - sculptcore
  - scripts
  - tests

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - unrs-resolver

patchedDependencies:
  eslint-plugin-prettier: patches/eslint-plugin-prettier.patch
