packages:
  - addons/*
  - sculptcore/tests
  - sculptcore/source/litestl/binding/typescriptRuntime
  - sculptcore/source/litestl/tests
  - sculptcore/typescript
  - sculptcore
  - sculptcore/tests/testViewer3D
  - scripts
  - scripts/path.ux
  - tests
  - vendor/nstructjs
  - scripts/mathl

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - '@kmamal/gpu'
  - nw

overrides:
  nstructjs: workspace:*

patchedDependencies:
  cmake-js@8.0.0: patches/cmake-js@8.0.0.patch
  eslint-plugin-prettier: patches/eslint-plugin-prettier.patch
