export function api_define_rendersettings(api: any): void;
export function api_define_meshelem(api: any): void;
export function api_define_meshvertex(api: any): void;
export function api_define_sceneobject_data(api: any, cls: any): any;
export function api_define_imageuser(api: any): any;
export function api_define_image(api: any): void;
export function api_define_bvhsettings(api: any): void;
export function api_define_mesh(api: any, pstruct: any): void;
export function api_define_curvespline(api: any): any;
export function api_define_camera(api: any): void;
export function api_define_cameradata(api: any): void;
export function api_define_velpan(api: any, parent: any): any;
export function api_define_screen(api: any, parent: any): void;
export function api_define_envlight(api: any): any;
export function api_define_light(api: any, pstruct: any): void;
export function api_define_scene(api: any, pstruct: any): void;
export function api_define_dyntopo(api: any): void;
export function api_define_brush(api: any, cstruct: any): void;
export function api_define_matrix4(api: any): any;
export function getDataAPI(): DataAPI;
import { DataAPI } from '../path.ux/scripts/pathux.js';
