"use strict";

import {setIconMap} from '../path.ux/scripts/ui_base.js';

export let Icons = {
  HFLIP          : 0,
  TRANSLATE      : 1,
  ROTATE         : 2,
  HELP_PICKER    : 3,
  UNDO           : 4,
  REDO           : 5,
  CIRCLE_SEL     : 6,
  BACKSPACE      : 7,
  LEFT_ARROW     : 8,
  RIGHT_ARROW    : 9,
  UI_EXPAND      : 10, //triangle
  UI_COLLAPSE    : 11, //triangle
  FILTER_SEL_OPS : 12,
  SCROLL_DOWN    : 13,
  SCROLL_UP      : 14,
  NOTE_EXCL      : 15,
  TINY_X         : 16,
  FOLDER         : 17,
  FILE           : 18,
  SMALL_PLUS     : 19,
  SMALL_MINUS    : 20,
  MAKE_SEGMENT   : 21,
  MAKE_POLYGON   : 22,
  FACE_MODE      : 23,
  EDGE_MODE      : 24,
  VERT_MODE      : 25,
  CURSOR_ARROW   : 26,
  TOGGLE_SEL_ALL : 27,
  DELETE         : 28,
  RESIZE         : 29,
  Z_UP           : 30,
  Z_DOWN         : 31,
  SPLIT_EDGE     : 32,
  SHOW_ANIMPATHS : 33,
  UNCHECKED      : 34,
  CHECKED        : 35,
  ENUM_UNCHECKED : 36,
  ENUM_CHECKED   : 37,
  APPEND_VERTEX  : 38,
  VIEW_SELECTED  : 39,
  EXTRUDE        : 40,
  SUBDIVIDE      : 41,
  SUBSURF        : 42,
  LIGHT          : 43,
  RENDER         : 44,
  VIEW_RAW       : 45,
  VIEW_NORMALS   : 46,
  VIEW_DEPTH     : 47,
  VIEW_ALPHA     : 48,
  SCALE_WIDGET   : 49,
  FAKE_USER      : 50,
  PAN            : 51,
  MEASURE_ANGLE  : 52,
  OPEN_FILE      : 53,
  SAVE_FILE      : 54,
  MATERIAL       : 55,
  OBJECT         : 56,
  MEASURE_TOOLS  : 57,
  CLIP_TOOLS     : 58,
  VIEWS          : 59,
  VIEW_TOOLS     : 60,
  SHOW_GRID      : 61,
  PERSPECTIVE    : 62,
  ORTHOGRAPHIC   : 63,
  MEASURE_DIST   : 64,
  RESET          : 65
};
setIconMap(Icons);
