/**WARNING: autogenerated file*/

import {readOBJ} from '../util/objloader.js'
import type {SimpleMesh} from './simplemesh'
import {ShapeOBJs} from './shape_data'

/**loadShapes will put widget meshes here, with the same keys as in
   ShapeOBJs*/
export const Shapes = {} as {[k in keyof typeof ShapeOBJs]: SimpleMesh}

export function loadShapes() {
  const ShapeSources = ShapeOBJs as {[k: string]: string}
  for (let k in ShapeSources) {
    let buf = ShapeSources[k]
    buf = atob(buf)

    Shapes[k as keyof typeof ShapeOBJs] = readOBJ(buf).genRender(undefined, true)
  }
}
