/**WARNING: autogenerated file*/

import type {SimpleMesh} from './simplemesh'
import {ShapeOBJs} from './shape_data'

// Late-bound by the mesh addon to avoid a static dependency from this file
// (which framework_api.ts re-exports as `Shapes`) into mesh.ts, which would
// create a TDZ cycle when mesh.ts itself imports from `@framework/api`.
let _readOBJ: ((buf: string) => {genRender(_: undefined, b: boolean): SimpleMesh}) | undefined
export function setShapesObjLoader(fn: typeof _readOBJ): void {
  _readOBJ = fn
}

/**loadShapes will put widget meshes here, with the same keys as in
   ShapeOBJs*/
export const Shapes = {} as {[k in keyof typeof ShapeOBJs]: SimpleMesh}

export function loadShapes() {
  if (!_readOBJ) {
    throw new Error('loadShapes called before setShapesObjLoader; ensure mesh addon registered.')
  }
  const ShapeSources = ShapeOBJs as {[k: string]: string}
  for (let k in ShapeSources) {
    let buf = ShapeSources[k]
    buf = atob(buf)

    Shapes[k as keyof typeof ShapeOBJs] = _readOBJ(buf).genRender(undefined, true)
  }
}
