/**
 * esbuild plugin that resolves `@addon/<id>/api` imports inside consumer-addon
 * bundles to a small runtime-lookup stub instead of inlining the upstream
 * addon's source. See plan §2.5 / deferred follow-up #2.
 *
 * Build time:
 *   - The plugin matches imports of `@addon/<id>/api`.
 *   - It reads `addons/builtin/<id>/src/api.ts` and parses its export names
 *     (named exports + `export * as ns` + named re-exports + class/function/
 *     const/enum). Type-only exports are filtered — they don't need runtime
 *     bindings.
 *   - It emits a tiny stub module that exports each name as a value sourced
 *     from `globalThis._addons.getAddonAPI('<id>').exports['<id>']`. The
 *     lookup runs at the consumer module's load time, by which point the
 *     dependency has already loaded (the AddonManager topo-sorts manifests
 *     before importing each addon, plan §2.5).
 *
 * Runtime:
 *   - The consumer module sees real `export const X = ...` statements with
 *     real values, so `import {X} from '@addon/mesh/api'` works statically.
 *   - No mesh code is duplicated into the consumer bundle. The mesh subsystem
 *     ships once (today in the main bundle as an internal builtin; in a
 *     future step as its own per-addon bundle).
 *
 * Limitations:
 *   - Late binding: if the consumer reaches into `@addon/mesh/api` *before*
 *     the dependency is registered, the lookup yields `undefined`. The
 *     manifest dependency declaration is what guarantees ordering.
 *   - Default exports are not currently supported (mesh's api.ts uses
 *     named-only). Add `export default` handling if/when an addon needs it.
 */

import fs from 'node:fs'
import path from 'node:path'

/**
 * @param {string} repoRoot - absolute path to the repo root.
 * @returns {import('esbuild').Plugin}
 */
export function addonApiPlugin(repoRoot) {
  const filter = /^@addon\/([^/]+)\/api$/
  const namespace = 'addon-api'

  return {
    name: 'addon-api',
    setup(build) {
      build.onResolve({filter}, (args) => {
        const id = args.path.match(filter)[1]
        return {path: id, namespace}
      })

      build.onLoad({filter: /.*/, namespace}, (args) => {
        const id = args.path
        const apiFile = path.join(repoRoot, 'addons', 'builtin', id, 'src', 'api.ts')
        if (!fs.existsSync(apiFile)) {
          return {
            errors: [
              {text: `@addon/${id}/api resolver: ${path.relative(repoRoot, apiFile)} does not exist`},
            ],
          }
        }

        let src
        try {
          src = fs.readFileSync(apiFile, 'utf-8')
        } catch (err) {
          return {errors: [{text: `@addon/${id}/api: ${err.message}`}]}
        }

        const names = parseExportNames(src)
        if (names.length === 0) {
          return {errors: [{text: `@addon/${id}/api: no value exports found in ${apiFile}`}]}
        }

        const idLit = JSON.stringify(id)
        const lines = [
          `// Generated by tools/addon_api_plugin.js — do not edit.`,
          `const __api = (globalThis._addons && globalThis._addons.getAddonAPI && globalThis._addons.getAddonAPI(${idLit})) || null`,
          `const __ns = (__api && __api.exports && __api.exports[${idLit}]) || {}`,
          ...names.map((n) => `export const ${n} = __ns[${JSON.stringify(n)}]`),
        ]

        return {contents: lines.join('\n') + '\n', loader: 'js', watchFiles: [apiFile]}
      })
    },
  }
}

/**
 * Parses an api.ts to extract every *value* export name. Filters out
 * type-only exports since those don't exist at runtime.
 *
 * Handles:
 *   export { A, B, C as D } from '...'        // value re-export
 *   export type { ... } from '...'            // type-only — SKIPPED
 *   export * as ns from '...'                 // namespace value
 *   export type * as ns from '...'            // type-only namespace — SKIPPED
 *   export const X = ...
 *   export let X = ... / export var X = ...
 *   export function X(...)
 *   export class X
 *   export enum X
 *   export abstract class X
 *   export default ...                        // SKIPPED with warning
 *
 * Strips // line comments and / *...* / block comments before scanning so
 * commented-out export lines don't pollute the name set.
 *
 * @returns {string[]}
 */
export function parseExportNames(src) {
  const names = new Set()

  // Strip block comments first (greedy across newlines).
  let cleaned = src.replace(/\/\*[\s\S]*?\*\//g, '')
  // Then line comments.
  cleaned = cleaned.replace(/(^|[^:\/])\/\/[^\n]*/g, '$1')

  // Named re-export: `export {A, B} from '...'` (no `type` keyword).
  // Per-item `type ` aliasing inside the braces is excluded.
  const reexportRe = /export\s+\{([^}]+)\}\s+from\s+['"][^'"]+['"]/g
  for (const m of cleaned.matchAll(reexportRe)) {
    for (const item of m[1].split(',')) {
      const t = item.trim()
      if (!t || /^type\b/.test(t)) continue
      const aliased = t.match(/^\S+\s+as\s+(\w+)$/)
      names.add(aliased ? aliased[1] : t)
    }
  }

  // Plain `export {A, B}` (no `from`). Same item-level rules.
  const localExportRe = /export\s+\{([^}]+)\}(?!\s+from)/g
  for (const m of cleaned.matchAll(localExportRe)) {
    for (const item of m[1].split(',')) {
      const t = item.trim()
      if (!t || /^type\b/.test(t)) continue
      const aliased = t.match(/^\S+\s+as\s+(\w+)$/)
      names.add(aliased ? aliased[1] : t)
    }
  }

  // `export * as foo from '...'` (value namespace re-export).
  for (const m of cleaned.matchAll(/export\s+\*\s+as\s+(\w+)\s+from\s+['"][^'"]+['"]/g)) {
    names.add(m[1])
  }

  // `export const|let|var|function|class|enum|abstract class NAME`.
  for (const m of cleaned.matchAll(
    /export\s+(?:declare\s+)?(?:abstract\s+)?(?:const|let|var|function|class|enum)\s+(\w+)/g
  )) {
    names.add(m[1])
  }

  // Explicitly drop names that appear ONLY in `export type {...}` blocks.
  // The above patterns already skip the `export type` form, but if a value
  // export shadowed a name from a type re-export, the value wins (kept by
  // the Set).

  return Array.from(names)
}
