/**
 * esbuild plugin that resolves `@framework/api` (and `@framework/pathux`)
 * imports inside addon bundles to a runtime-lookup stub instead of inlining
 * the framework's source.
 *
 * Why this exists:
 *   Without this plugin, esbuild inlines `scripts/framework_api.ts` (and
 *   everything it transitively imports — all of scripts/, path.ux, the
 *   addon manager, nstructjs class registry, etc.) into every addon bundle,
 *   causing the framework to evaluate multiple times and produce
 *   duplicate singletons.
 *
 * Build time:
 *   - The plugin matches imports of `@framework/<surface>` for a fixed set
 *     of surfaces (`api`, `pathux`).
 *   - It reads the surface's source file (e.g. `scripts/framework_api.ts`)
 *     and statically extracts every value-export name. For `export * from
 *     './foo.js'` lines, it recurses into `foo.js` to collect names
 *     transitively. Type-only exports are skipped.
 *   - It emits a tiny stub module that exports each name as a value sourced
 *     from `globalThis._framework[<key>]`. The lookup runs at the consumer
 *     module's load time, by which point the main bundle has assigned
 *     `globalThis._framework` (see `scripts/_framework_runtime.ts`).
 *
 * Runtime:
 *   - The consumer module sees real `export const X = ...` statements with
 *     real values, so `import {X} from '@framework/api'` works statically.
 *   - No framework code is duplicated into the addon bundle.
 *
 * Limitations:
 *   - Late binding: if an addon reaches into `@framework/api` *before*
 *     `_framework_runtime.ts` runs in the main bundle, the lookup yields
 *     `undefined`. The main bundle imports `_framework_runtime.ts` from
 *     `scripts/entry_point.js` ahead of any addon-register side effects,
 *     so this only bites if someone wires things up out of order.
 *   - Default exports are not supported.
 *   - `export *` recursion bottoms out at non-resolvable specifiers
 *     (anything not relative or not found on disk).
 */

import fs from 'node:fs'
import path from 'node:path'

import {parseExportNames} from './addon_api_plugin.js'

/**
 * @typedef {{match: string, sourceFile: string, key: string}} SurfaceConfig
 */

/**
 * @param {string} repoRoot - absolute path to the repo root.
 * @returns {import('esbuild').Plugin}
 */
export function frameworkApiPlugin(repoRoot) {
  /** @type {SurfaceConfig[]} */
  const surfaces = [
    {
      match     : '@framework/api',
      sourceFile: path.join(repoRoot, 'scripts', 'framework_api.ts'),
      key       : 'api',
    },
    {
      match     : '@framework/pathux',
      sourceFile: path.join(repoRoot, 'scripts', 'path.ux', 'scripts', 'pathux.ts'),
      key       : 'pathux',
    },
  ]

  const byMatch = new Map(surfaces.map((s) => [s.match, s]))
  const namespace = 'framework-api'
  const filter = /^@framework\/(api|pathux)$/

  return {
    name: 'framework-api',
    setup(build) {
      build.onResolve({filter}, (args) => {
        return {path: args.path, namespace}
      })

      build.onLoad({filter: /.*/, namespace}, (args) => {
        const surface = byMatch.get(args.path)
        if (!surface) {
          return {errors: [{text: `framework-api: no surface registered for "${args.path}"`}]}
        }
        if (!fs.existsSync(surface.sourceFile)) {
          return {
            errors: [
              {
                text: `framework-api: ${path.relative(repoRoot, surface.sourceFile)} does not exist`,
              },
            ],
          }
        }

        /** @type {Set<string>} */
        const visited = new Set()
        /** @type {string[]} */
        const watchFiles = []
        let names
        try {
          names = collectExports(surface.sourceFile, visited, watchFiles)
        } catch (err) {
          return {errors: [{text: `framework-api(${surface.key}): ${err.message}`}]}
        }
        if (names.length === 0) {
          return {
            errors: [{text: `framework-api(${surface.key}): no value exports found in ${surface.sourceFile}`}],
          }
        }

        const keyLit = JSON.stringify(surface.key)
        const lines = [
          `// Generated by tools/framework_api_plugin.js — do not edit.`,
          `const __ns = (globalThis._framework && globalThis._framework[${keyLit}]) || {}`,
          `if (typeof globalThis._framework === 'undefined' || !globalThis._framework[${keyLit}]) {`,
          `  console.warn('framework-api: globalThis._framework[' + ${keyLit} + '] is not set; addon will see undefined exports.')`,
          `}`,
          ...names.map((n) => `export const ${n} = __ns[${JSON.stringify(n)}]`),
        ]

        return {contents: lines.join('\n') + '\n', loader: 'js', watchFiles}
      })
    },
  }
}

/**
 * Recursively collects value-export names from a source file. Handles
 * `export * from '...'` by reading the target file and merging.
 *
 * @param {string} file - absolute path to source file
 * @param {Set<string>} visited - cycle guard
 * @param {string[]} watchFiles - files to watch (mutated)
 * @returns {string[]}
 */
function collectExports(file, visited, watchFiles) {
  if (visited.has(file)) return []
  visited.add(file)
  watchFiles.push(file)

  const src = fs.readFileSync(file, 'utf-8')
  const names = new Set(parseExportNames(src))

  // Recurse into `export * from '<relative>'` (but NOT `export * as ns from`
  // or `export type * from`, both of which are handled / skipped by the
  // base parser already).
  const cleaned = stripComments(src)
  const starRe = /export\s+\*\s+from\s+['"]([^'"]+)['"]/g
  for (const m of cleaned.matchAll(starRe)) {
    const spec = m[1]
    const resolved = resolveSpecifier(file, spec)
    if (!resolved) {
      // Non-relative or unresolvable — skip silently. In practice the
      // framework's `export *` lines are always relative.
      continue
    }
    for (const n of collectExports(resolved, visited, watchFiles)) {
      names.add(n)
    }
  }

  return [...names]
}

function stripComments(src) {
  let s = src.replace(/\/\*[\s\S]*?\*\//g, '')
  s = s.replace(/(^|[^:\/])\/\/[^\n]*/g, '$1')
  return s
}

/**
 * Resolves a relative import specifier from `fromFile` to an absolute path
 * on disk. Tries the literal path first (after rewriting .js → .ts), then
 * common extensions, then `<spec>/index.ts|js`.
 *
 * @param {string} fromFile
 * @param {string} spec
 * @returns {string | null}
 */
function resolveSpecifier(fromFile, spec) {
  if (!spec.startsWith('.') && !spec.startsWith('/')) return null
  const base = path.resolve(path.dirname(fromFile), spec)

  // TS source resolution: .js specifier often points at a .ts file.
  const candidates = []
  const ext = path.extname(base)
  if (ext) {
    candidates.push(base)
    // .js → also try .ts / .tsx
    if (ext === '.js') {
      const stem = base.slice(0, -3)
      candidates.push(stem + '.ts', stem + '.tsx')
    }
  } else {
    candidates.push(base + '.ts', base + '.tsx', base + '.js', base + '.mjs')
    candidates.push(path.join(base, 'index.ts'))
    candidates.push(path.join(base, 'index.tsx'))
    candidates.push(path.join(base, 'index.js'))
  }

  for (const c of candidates) {
    if (fs.existsSync(c) && fs.statSync(c).isFile()) return c
  }
  return null
}
